### ISSUE TITLE
Control input errors

### ISSUE THREAD

**Issue by melissceylan** [Calendar-Project/Calendar#23]

**Comment by ElifHangul** [comment]
Validation for input is added. If no title, start date, start time, end date or end time is added, create new appointment or update an appointment functions does not work and app fires an error message.

**Comment by ElifHangul** [comment]
Date and time pickers are linked together. The default value is set to today's date, start time 08:00, end time 09:00. The minimum value of end date is set to the start date. Similarly the minimum value of end time is set to start time.

**Comment by ElifHangul** [comment]
Links between pages are changed. A delete link is added to each appointment page. After editing or deleting the appointment, returned to the main calendar page.

**Comment by ElifHangul** [comment]
Default dates for date pickers were today's date. But in the edit page the default values should be the first committed dates. Therefore the default values for edit and create pages are changed.

**Comment by ElifHangul** [comment]
End time had to be later then start time in the same day. But if the end day is a later day than the start day, then end time could be any time. This difference is corrected.

**Comment by ElifHangul** [comment]
Delete function was only working locally, not in Heroku. Delete function is made functional in Heroku.

**Comment by ElifHangul** [comment]
The start page datepicker now shows the selected date not the default today's date.
