### ISSUE TITLE
Create recurring appointments 

### ISSUE THREAD

**Issue by melissceylan** [Calendar-Project/Calendar#25]

**Comment by ElifHangul** [comment]
Weekly appointment repeat is added. On an existing appointment show page, when the repeat weekly tab is clicked the appointment repeats itself every week in the appointment's month.

**Comment by ElifHangul** [comment]
Monthly appointment repeat is added. On an existing appointment show page, when the repeat monthly tab is clicked the appointment repeats itself every month of the appointment's year
